# MQTT Connection, if empty will query and use hassio provided mqtt
mqtt:
  host:
  port: 1883
  ssl: false
  username: mqtt-user
  password: mqtt-user

# This gets added to the x,y,z to derive a gps location

  latitude: 39.631313
  longitude: -78.765831
  elevation: 236
  rotation: 10 # Rotation in degrees from north (0 degrees)
  report: false # Include GPS latitude/longitude when reporting to Home Assistant

map:
  flip_x: false        # Set to true to flip X coordinates (default: false)
  flip_y: true         # Set to true to use bottom-left origin, false for top-left origin (default: true)
  wall_thickness: 0.1  # Wall thickness in meters
  wall_color: "#ddd"   # Optional wall color, if not set uses room color
  wall_opacity: 0.35   # Optional wall opacity, if not set defaults to 0.35

# How long before device considered stale
timeout: 30
# How long before device is considered away
away_timeout: 120

optimization:
  enabled: true
  interval_secs: 3600
  keep_snapshot_mins: 5   # How long to keep optimization snapshots (default: 5 minutes)
  optimizer: per_node_absorption # Options global_absorption, per_node_absorption, legacy (default: legacy)
  limits:
    absorption_min: 2.5
    absorption_max: 3.5
    rx_adj_rssi_min: -5
    rx_adj_rssi_max: 25
    tx_ref_rssi_min: -80
    tx_ref_rssi_max: -40
  weights:
    # Weighting factor for Pearson Correlation in best scenario scoring (default: 0.5)
    correlation: 0.5
    # Weighting factor for normalized RMSE in best scenario scoring (default: 0.5)
    rmse: 0.5

history:
  enabled: false # Enable to log history to db (Beta)
  expire_after: 24h # Expire after 24 hours

locators:
  nadaraya_watson:
    enabled: true
    floors: ["first", "second"]
    bandwidth: 0.5
    kernel: gaussian

  nelder_mead:
    enabled: false
    floors: ["first", "second"]
    weighting:
      algorithm: gaussian
      props:
        sigma: 0.10

  nearest_node:
    enabled: true
    max_distance: 10

# Floors w/ the points to draw it in meters
floors:
  - id: first
    name: First Floor
    # Bounds (x,y,z) of map in meters
    bounds: [[0, 0, 0], [17, 18, 3]]
    rooms:
      - name: Living
        # Optional room color in hex; if omitted, server assigns a deterministic color
        # color: "#1F77B4"
        points:
          - [ 0, 10.61]
          - [ 7.06, 10.61]
          - [ 7.06, 6.57]
          - [ 0, 6.57]
          - [ 0, 10.61]
      - name: Kitchen
        points:
          - [ 0.01, 6.57]
          - [ 3.24, 6.57]
          - [ 3.24, 0]
          - [ 0.01, 0]
          - [ 0.01, 6.57]
      - name: Dining
        points:
          - [ 3.24, 6.57]
          - [ 7.06, 6.57]
          - [ 7.06, 3.08]
          - [ 3.24, 3.08]
          - [ 3.24, 6.57]
  - id: second
    # name: Second Floor
    # bounds: [[0, 0, 3], [17, 18, 5.5]]
    # rooms:
    #   - name: Master
    #     points:
    #       - [3.2,7.6]
    #       - [3.2,12.3]
    #       - [6.3,12.3]
    #       - [6.3,10.2]
    #       - [8.4,10.2]
    #       - [8.4,9]
    #       - [6.9,7.6]
    #       - [3.7,7.6]
    #   - name: Office
    #     points:
    #       - [6.3,14]
    #       - [9.9,14]
    #       - [9.9,12.7]
    #       - [9.8,12.7]
    #       - [9.8,11.5]
    #       - [8.4,10.2]
    #       - [6.3,10.2]
    #   - name: Master Bathroom
    #     points:
    #       - [0, 7.6]
    #       - [0, 12.3]
    #       - [3.2, 12.3]
    #       - [3.2, 7.6]
    #   - name: Master Closet
    #     points:
    #       - [1.3,12.3]
    #       - [5,12.3]
    #       - [5,17.1]
    #       - [1.3,17.1]

# Locations of espresense nodes in meters
nodes:
  - name: Living Room
    point: [7.01,9.25, 0.48]
    floors: ["first"]
  - name: Dining Room
    point: [7.01,3.98, 0]
    floors: ["first"]
  - name: Kitchen
    point: [0.01,1.55, 0]
    floors: ["first"]
  # - name: Basement
  #   point: [15.8, 11.5, -0.5]
  #   floors: ["first"]
  # - name: Laundry
  #   point: [4.3, 7.6, 1]
  #   floors: ["first"]
  # - name: Back Stairs
  #   point: [4.5, 7.5, 3.4]
  #   floors: ["first", "second"]
  # - name: Foyer
  #   point: [9.9, 8.3, 0.4]
  #   floors: ["first", "second"]
  # - name: VW EOS
  #   stationary: false
  #   point: [-2, 15, 0.5]
  #   floors: ["first"]

# Devices to track
devices:
  - name: "*" # Track all named devices
  - id: "tile:*" # Track all tiles
  - id: "irk:*" # Track all IRKs
  - id: "watch:*"
  - id: "phone:*"
  - id: "wallet:*"
  - id: "keys:*"
  - id: "therm:*"
  - id: "iBeacon:*"
  - id: "car:*"
  - id: "laptop:*"
  - id: "itag:f0f010303080"
    name: "Piper's Backpack"

# Devices to NOT track
exclude_devices:
  - id: "iBeacon:e5ca1ade-f007-ba11-0000-000000000000-*" # These are junk, we alias them to node:*
